/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import MainHome.MainForm;
import Utils.DBMange;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Saif Eldin
 */
public class OrderScreen extends javax.swing.JFrame {

    /**
     * Creates new form OrderScreen
     */
    String id,details,date,customerid,orderCase;
    public static boolean IsUpdated;
    //
        
    public OrderScreen() {
        initComponents();
        // to make screen in center
        this.setLocationRelativeTo(null); 
    }
    public OrderScreen(String id) {
        initComponents();
        // to make screen in center
        this.setLocationRelativeTo(null); 
        this.id = id; 
        orderid2.setText(id);
        IsUpdated=false;
        
        // to make screen in center
        this.setLocationRelativeTo(null); 
    }
    
    public void InsertData(){
        id = orderid2.getText();
        details = orderdetails2.getText();
        date = orderdate2.getText();
        customerid = custid2.getText();
        orderCase = ordercase2.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorfulBackGround3 = new Utils.ColorfulBackGround();
        llll = new javax.swing.JLabel();
        orderdetail = new javax.swing.JLabel();
        ordercase = new javax.swing.JLabel();
        orderdate = new javax.swing.JLabel();
        custid = new javax.swing.JLabel();
        orderdetails2 = new javax.swing.JTextField();
        orderdate2 = new javax.swing.JTextField();
        orderid2 = new javax.swing.JTextField();
        ordercase2 = new javax.swing.JTextField();
        custid2 = new javax.swing.JTextField();
        insertbtn2 = new javax.swing.JButton();
        viewbtn2 = new javax.swing.JButton();
        deletebtn2 = new javax.swing.JButton();
        updatebtn2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        llll.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        llll.setForeground(new java.awt.Color(255, 255, 255));
        llll.setText("Order Id");

        orderdetail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        orderdetail.setForeground(new java.awt.Color(255, 255, 255));
        orderdetail.setText("Order Details");

        ordercase.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ordercase.setForeground(new java.awt.Color(255, 255, 255));
        ordercase.setText("Order Case");

        orderdate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        orderdate.setForeground(new java.awt.Color(255, 255, 255));
        orderdate.setText("Order Date");

        custid.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        custid.setForeground(new java.awt.Color(255, 255, 255));
        custid.setText("Customer Id");

        orderdetails2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        orderdetails2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        orderdate2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        orderdate2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        orderid2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        orderid2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ordercase2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ordercase2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        custid2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        custid2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        insertbtn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        insertbtn2.setText("Insert Order");
        insertbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertbtnMouseClicked(evt);
            }
        });

        viewbtn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        viewbtn2.setText("View Order");
        viewbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewbtnMouseClicked(evt);
            }
        });

        deletebtn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        deletebtn2.setText("Delete Order");
        deletebtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebtnMouseClicked(evt);
            }
        });

        updatebtn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        updatebtn2.setText("Update Order");
        updatebtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebtnMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/order.png"))); // NOI18N
        jLabel16.setText(" Manage Your Orders");

        javax.swing.GroupLayout colorfulBackGround3Layout = new javax.swing.GroupLayout(colorfulBackGround3);
        colorfulBackGround3.setLayout(colorfulBackGround3Layout);
        colorfulBackGround3Layout.setHorizontalGroup(
            colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorfulBackGround3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(orderdate)
                        .addGroup(colorfulBackGround3Layout.createSequentialGroup()
                            .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorfulBackGround3Layout.createSequentialGroup()
                                    .addComponent(llll)
                                    .addGap(182, 182, 182))
                                .addGroup(colorfulBackGround3Layout.createSequentialGroup()
                                    .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(orderdetail)
                                        .addComponent(orderdetails2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(custid)
                                .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ordercase2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ordercase, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(custid2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(colorfulBackGround3Layout.createSequentialGroup()
                        .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderid2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(182, 182, 182)
                .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorfulBackGround3Layout.createSequentialGroup()
                        .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(insertbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletebtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorfulBackGround3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(257, 257, 257))
        );
        colorfulBackGround3Layout.setVerticalGroup(
            colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorfulBackGround3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel16)
                .addGap(47, 47, 47)
                .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorfulBackGround3Layout.createSequentialGroup()
                        .addComponent(insertbtn2)
                        .addGap(43, 43, 43)
                        .addComponent(deletebtn2)
                        .addGap(49, 49, 49)
                        .addComponent(viewbtn2))
                    .addGroup(colorfulBackGround3Layout.createSequentialGroup()
                        .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llll)
                            .addComponent(ordercase))
                        .addGap(18, 18, 18)
                        .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orderid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ordercase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(colorfulBackGround3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(colorfulBackGround3Layout.createSequentialGroup()
                                .addComponent(custid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(colorfulBackGround3Layout.createSequentialGroup()
                                .addComponent(orderdetail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderdetails2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orderdate)
                        .addGap(27, 27, 27)
                        .addComponent(orderdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updatebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(colorfulBackGround3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(colorfulBackGround3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertbtnMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_insertbtnMouseClicked

    private void deletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseClicked
        // TODO add your handling code here:
        InsertData();
        DBMange db = new DBMange();
        String msg = db.runInsUpDel("delete from orders where orderid = '"+id+"'");
        if(msg.equals("OK")){
            JOptionPane.showMessageDialog(rootPane, "your order is deleted");
        }else{
            JOptionPane.showMessageDialog(rootPane, msg);
        }
        
    }//GEN-LAST:event_deletebtnMouseClicked

    private void viewbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbtnMouseClicked
        // TODO add your handling code here:
        try{
         String id;
        id = orderid2.getText();
        DBMange db = new DBMange();
        ResultSet msg = db.runSelect("select * from orders where orderid = '"+id+"' ");
        if(msg.next()){
            custid2.setText(msg.getString(5));
            ordercase2.setText(msg.getString(4));
            orderdate2.setText(msg.getString(3));
            orderdetails2.setText(msg.getString(2));
        }else{
            JOptionPane.showMessageDialog(rootPane, msg+" ddd ");
            System.out.println();
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            System.out.println(e.getMessage());
        } 
    }//GEN-LAST:event_viewbtnMouseClicked

    private void updatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseClicked
        // TODO add your handling code here:
        InsertData();
        DBMange db = new DBMange();
        String msg = db.runInsUpDel("update orders set orderdetails='"+ details +"' ,orderdate='"+ date +"' ,ordercase='"+orderCase +"' ,ordercustid='"+ customerid +"' "
                + "where  orderid= '"+ id +"' ");
        if(msg.equals("OK")){
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/checkicon.png"));
            JOptionPane.showMessageDialog(rootPane, "your order is updated","Updated"
                    ,JOptionPane.INFORMATION_MESSAGE,icon);
            
        }else{
            JOptionPane.showMessageDialog(rootPane, msg);
        }
        
    }//GEN-LAST:event_updatebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderScreen().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Utils.ColorfulBackGround colorfulBackGround3;
    private javax.swing.JLabel custid;
    private javax.swing.JTextField custid2;
    private javax.swing.JButton deletebtn2;
    private javax.swing.JButton insertbtn2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel llll;
    private javax.swing.JLabel ordercase;
    private javax.swing.JTextField ordercase2;
    private javax.swing.JLabel orderdate;
    private javax.swing.JTextField orderdate2;
    private javax.swing.JLabel orderdetail;
    private javax.swing.JTextField orderdetails2;
    private javax.swing.JTextField orderid2;
    private javax.swing.JButton updatebtn2;
    private javax.swing.JButton viewbtn2;
    // End of variables declaration//GEN-END:variables

 
}
